version: '3.7'

services:
  web:
    build: ./coffeshop
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./coffeshop/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=coffee_shop
      - POSTGRES_PASSWORD=coffee_shop@123
      - POSTGRES_DB=coffee_shop

volumes:
  postgres_data:
