# Generated by Django 3.1.4 on 2021-01-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210105_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='drink_count',
        ),
    ]
