# Generated by Django 3.1.4 on 2021-04-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210105_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_drink',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
