# Generated by Django 3.1.4 on 2021-04-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210419_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdrink',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
