# Generated by Django 3.1.4 on 2021-04-20 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20210420_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdrink',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
